name: Cut Prod Branch

on: [workflow_dispatch]

jobs:
  cut:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cut branch
        run: |
          git checkout main || true
          git tag $(date -u +'release/%Y-%m-%d-T%H-%M-%SZ')
          git branch -D prod || true
          git checkout -b prod
          git push --force --tags --set-upstream origin +prod
